"""create_workspace_tables

Revision ID: 3ec8b3aaa12b
Revises: 
Create Date: 2026-01-08 15:29:10.341779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ec8b3aaa12b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_index(op.f('ix_workspace_owner_id'), 'workspace', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workspace_slug'), 'workspace', ['slug'], unique=True)
    op.create_index(op.f('ix_workspace_type'), 'workspace', ['type'], unique=False)
    op.create_table('workspace_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_member_user_id'), 'workspace_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    
    # Alter calculation table: drop old FK, add new column and FK
    op.drop_constraint('fk_calculation_organization', 'calculation', type_='foreignkey')
    op.drop_column('calculation', 'organization_id')
    op.add_column('calculation', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_calculation_created_by_user_id'), 'calculation', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_calculation_workspace_id'), 'calculation', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'calculation', 'workspace', ['workspace_id'], ['id'])
    
    # Drop organization table (now no dependencies)
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_slug'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calculation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_calculation_organization'), 'calculation', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_calculation_workspace_id'), table_name='calculation')
    op.drop_index(op.f('ix_calculation_created_by_user_id'), table_name='calculation')
    op.drop_column('calculation', 'workspace_id')
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('organization_created_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_pkey'))
    )
    op.create_index(op.f('ix_organization_slug'), 'organization', ['slug'], unique=True)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.drop_index(op.f('ix_workspace_member_workspace_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_user_id'), table_name='workspace_member')
    op.drop_table('workspace_member')
    op.drop_index(op.f('ix_workspace_type'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_slug'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_owner_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_table('workspace')
    # ### end Alembic commands ###
